import type { Flight } from "@/lib/work";

type Seed = Pick<Flight, "slug" | "title" | "location" | "category" | "kit" | "still" | "clip" | "alt"> & Partial<Pick<Flight, "wide" | "note">>;

const SEEDS: Seed[] = [
  {
    slug: "chimney-stack-audit",
    title: "Chimney stack audit",
    location: "Power station, Madhya Pradesh",
    category: "Industrial",
    kit: "Thermal and 4K",
    still: "plant-chimneys.jpg",
    clip: "plant-chimneys.mp4",
    alt: "Drone view down the side of a concrete chimney stack beside a river and expressway",
    wide: true,
    note: "Full-height visual and thermal pass of the stack, no scaffolding.",
  },
  {
    slug: "metro-viaduct-tracking",
    title: "Metro viaduct tracking",
    location: "Bengaluru",
    category: "Urban and transit",
    kit: "4K",
    still: "metro-highway.jpg",
    clip: "metro-highway.mp4",
    alt: "Top-down view of a metro viaduct running above a busy highway",
  },
  {
    slug: "hill-temple",
    title: "Hill temple",
    location: "Western Ghats",
    category: "Scenic and heritage",
    kit: "6K",
    still: "hill-temple.jpg",
    clip: "hill-temple.mp4",
    alt: "Aerial view of a hilltop temple roof with mountains behind",
    note: "Slow rising reveal for a heritage documentary.",
  },
  {
    slug: "conveyor-line-survey",
    title: "Conveyor line survey",
    location: "Mineral processing unit",
    category: "Industrial",
    kit: "4K",
    still: "plant-conveyor.jpg",
    clip: "plant-conveyor.mp4",
    alt: "Looking down on rusted conveyor housings running through overgrown ground",
    wide: true,
  },
  {
    slug: "rail-yard-mapping",
    title: "Rail yard mapping",
    location: "Northern Railway hub",
    category: "Urban and transit",
    kit: "4K",
    still: "train-depot.jpg",
    clip: "train-depot.mp4",
    alt: "Overhead view of a rail yard with long depot sheds and parallel tracks",
  },
  {
    slug: "wetland-sanctuary",
    title: "Wetland sanctuary",
    location: "Chilika Lagoon",
    category: "Scenic and heritage",
    kit: "4K, telephoto",
    still: "river-birds.jpg",
    clip: "river-birds.mp4",
    alt: "Two birds flying low over still brown water",
  },
  {
    slug: "terminal-orbit",
    title: "Terminal orbit",
    location: "Nagpur",
    category: "Urban and transit",
    kit: "4K",
    still: "metro-station.jpg",
    clip: "metro-station.mp4",
    alt: "Transit terminal roof covered in solar panels next to a large parking lot",
    wide: true,
  },
  {
    slug: "tower-progress-survey",
    title: "Tower progress survey",
    location: "BKC, Mumbai",
    category: "Construction",
    kit: "4K",
    still: "highrise-towers.jpg",
    clip: "highrise-towers.mp4",
    alt: "Residential towers and a tower crane under an overcast sky",
  },
  {
    slug: "fpv-flythrough",
    title: "FPV flythrough",
    location: "Steel complex, Gujarat",
    category: "Industrial",
    kit: "7-inch FPV, 6K",
    still: "plant-fpv.jpg",
    clip: "plant-fpv.mp4",
    alt: "FPV flight through rusted steelwork inside an industrial plant",
  },
  {
    slug: "structural-steelwork-survey",
    title: "Structural steelwork survey",
    location: "Petrochem refinery",
    category: "Industrial",
    kit: "5.2K ProRes",
    still: "plant-structure.jpg",
    clip: "plant-structure.mp4",
    alt: "Steel pipework and structural framing across a refinery seen from above",
    wide: true,
  },
  {
    slug: "expressway-at-night",
    title: "Expressway at night",
    location: "Delhi NCR",
    category: "Urban and transit",
    kit: "4K, night",
    still: "night-highway.jpg",
    clip: "night-highway.mp4",
    alt: "Expressway running to the horizon at night, lit by moving traffic",
  },
  {
    slug: "river-basin-delta",
    title: "River basin delta",
    location: "Narmada Valley",
    category: "Scenic and heritage",
    kit: "6K",
    still: "river-sunset.jpg",
    clip: "river-sunset.mp4",
    alt: "Sunset over a wide river delta with green banks",
  },
];

/**
 * The flights the site launched with. The local store serves these until the first edit; production
 * is seeded with the same rows by supabase/migrations/20260929000000_admin.sql. Keep the two in step
 * (tests/admin.test.ts checks they still pass the admin's own rules).
 */
export const DEFAULT_FLIGHTS: Flight[] = SEEDS.map((s, i) => ({
  note: "",
  wide: false,
  ...s,
  id: s.slug,
  stillWidth: 0,
  stillHeight: 0,
  stillBlur: "",
  onHomepage: true,
  visible: true,
  position: i + 1,
}));
