#!/usr/bin/env node
/**
 * Builds lib/map/india.ts: India's outline as one SVG path, plus the projection that places points on it.
 *
 *   node scripts/india-outline.mjs <path to ne_10m_admin_0_countries_ind.geojson> [tolerance, default 1.6]
 *
 * Source: Natural Earth 1:10m admin-0 countries, *India point of view*
 * (github.com/nvkelso/natural-earth-vector, geojson/ne_10m_admin_0_countries_ind.geojson, public domain).
 * The IND view draws India's official boundary, including all of Jammu & Kashmir and Ladakh, which a map
 * published in India has to show. Do not swap in a default world map. The source file is 13 MB and is not
 * kept in the repo; only the simplified outline is.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const src = process.argv[2];
/** Simplification tolerance in viewBox units (1005 across); the map is shown ~560 px wide, so 1 unit is ~0.6 px. */
const TOL = Number(process.argv[3] ?? 1.6);
if (!src) {
  console.error("usage: node scripts/india-outline.mjs <ne_10m_admin_0_countries_ind.geojson>");
  process.exit(1);
}
const root = path.resolve(import.meta.dirname, "..");
const geo = JSON.parse(readFileSync(src, "utf8"));
const india = geo.features.find((f) => f.properties.ADM0_A3 === "IND");
if (!india) throw new Error("no IND feature in that file");

// Equirectangular, with longitude shortened by cos(22°) so shapes near the middle of India keep their proportions.
const LON0 = 68;
const LAT0 = 37.2;
const K = Math.cos((22 * Math.PI) / 180);
const S = 36; // viewBox units per degree of latitude
const PAD = 12;
const project = (lon, lat) => [PAD + (lon - LON0) * K * S, PAD + (LAT0 - lat) * S];

/** Douglas-Peucker on one ring, in viewBox units. */
function simplify(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy);
    let best = -1, far = 0;
    for (let i = a + 1; i < b; i++) {
      // A closed ring starts and ends on the same point, so the first "segment" has no length:
      // measure from that point instead of from a line that isn't there.
      const d = len === 0
        ? Math.hypot(pts[i][0] - ax, pts[i][1] - ay)
        : Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len;
      if (d > far) [far, best] = [d, i];
    }
    if (far > tol) {
      keep[best] = 1;
      stack.push([a, best], [best, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

const polys = india.geometry.type === "Polygon" ? [india.geometry.coordinates] : india.geometry.coordinates;
let d = "";
let points = 0;
let maxX = 0, maxY = 0;
for (const poly of polys) {
  // outer ring only: India's outline has no holes worth drawing at this size
  let ring = simplify(poly[0].map(([lon, lat]) => project(lon, lat)), TOL);
  if (ring.length < 4) ring = poly[0].map(([lon, lat]) => project(lon, lat)); // keep the smallest islands whole
  points += ring.length;
  d += "M" + ring.map(([x, y]) => {
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
    return `${x.toFixed(1)} ${y.toFixed(1)}`;
  }).join("L") + "Z";
}
const W = Math.ceil(maxX + PAD), H = Math.ceil(maxY + PAD);

const out = `// Generated by scripts/india-outline.mjs. Do not edit by hand.
// Source: Natural Earth 1:10m admin-0 countries, India point of view (public domain): India's official
// boundary, including all of Jammu & Kashmir and Ladakh. ${polys.length} polygons (mainland and islands), ${points} points.

export const INDIA_VIEWBOX = "0 0 ${W} ${H}";
export const INDIA_WIDTH = ${W};
export const INDIA_HEIGHT = ${H};

export const INDIA_PATH =
  "${d}";

/** Longitude/latitude to viewBox units, the same projection the outline was drawn with. */
export function project(lon: number, lat: number): [number, number] {
  return [${PAD} + (lon - ${LON0}) * ${K.toFixed(6)} * ${S}, ${PAD} + (${LAT0} - lat) * ${S}];
}
`;
mkdirSync(path.join(root, "lib/map"), { recursive: true });
writeFileSync(path.join(root, "lib/map/india.ts"), out);
console.log(`lib/map/india.ts: ${polys.length} polygons, ${points} points, viewBox ${W}x${H}, ${(out.length / 1024).toFixed(1)} KB`);
